EulerAEOS: Add precomputation of surrogate gamma.
conservation-laws/ryujin pull request #178
Opened 2024-10-01 17:58 UTC by ejtovar

2024-10-01 18:16 UTC, tamiko commented
@ejtovar Looking good. Let me check how this behaves on my Intel desktop. We'll need to fix some build issues :-)

2024-10-01 18:16 UTC, ejtovar commented
@tamiko Just fixed the build issues!

2024-10-03 22:44 UTC, tamiko requested changes

2024-10-03 22:44 UTC, tamiko commented on source/euler_aeos/hyperbolic_system.h
> -            const auto gamma_j = surrogate_gamma(U_j, p_j);
We have to balance this recomputation of `surrogate_gamma(U_j, p_j)` with the increased pressure on memory access. Unfortunately, I do see a roughly 0.5% performance regression in 2D and 3D with this change. So it is not making things faster.

2024-10-04 22:35 UTC, closed without merging